# Site Configs

port:         3999
host:         127.0.0.1

safe:          true
lsi:           false
markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

markdown_ext:  md,markdown
pygments:      false
paginate:      5

name:        Realschule Düsseldorf Golzheim
description: Homepage der Realschule Düsseldorf Golzheim
schulname:   Realschule Düsseldorf Golzheim Terstegenstraße

blog:        /aktuell
permalink:   /aktuell/:year/:month/:day/:title/
schule:      /schule

url:         http://www.schulen.duesseldorf.de/rs-tersteegenstr/v2
# url: ""


